[camera]
FOV = 136

[camera.position]
x = -1.9762939704993892
y = 3.7455000000017935
z = 25.51011231694712
w = 1.0

[camera.rotation]
x = -2.9920000000015476
y = 361.52299999999667
z = 0.0
w = 1.0
[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = -10.0
z = -10.0
w = 1.0
