title = "app settings"

[camera]
FOV = 90.0

[camera.position]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[camera.rotation]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 0.0
