[camera]
FOV = 150

[camera.position]
x = 21.695270064850465
y = 4.0
z = 13.03913937721513
w = 1.0

[camera.rotation]
x = 3251.0499999999893
y = -407.95000000000385
z = 0.0
w = 1.0
[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0
