title = "app settings"

[camera]
FOV = 150

[camera.position]
x = 17.657863441807912
y = 4.0
z = 17.086460007966053
w = 1.0

[camera.rotation]
x = 3249.149999999988
y = -386.75000000000466
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0
