[camera]
FOV = 150

[camera.position]
x = -2.063154181373171
y = 2.997500000001793
z = 39.75340856055676
w = 1.0

[camera.rotation]
x = 0.0
y = -368.89999999999924
z = 0.0
w = 1.0
[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 0.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 10.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 30.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 30.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = -10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = 10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = 10.0
z = 30.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = -10.0
z = 30.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = -10.0
y = -10.0
z = -10.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 0.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 30.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = -10.0
z = 30.0
w = 1.0

[[room.walls]]
tomlMessage = "start of new wall"

[[room.walls.corners]]
x = -10.0
y = 10.0
z = 30.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 10.0
z = 30.0
w = 1.0

[[room.walls.corners]]
x = 0.0
y = 0.0
z = 30.0
w = 1.0

[[room.walls.corners]]
x = -10.0
y = -10.0
z = 30.0
w = 1.0
